from TelegramBot.Handlers.StartBot import StartBot
from TelegramBot.Handlers.HelpComma import HelpComma
from TelegramBot.Handlers.ChooseMethod import ChooseMethod
from TelegramBot.Handlers.Random.RandomTranslate import RandomTranslate
from TelegramBot.Handlers.Auto.AutoTranslateText import AutoTranslateText
from TelegramBot.Handlers.Auto.AutoEndLangChoose import AutoEndLangChoose
from TelegramBot.Handlers.Auto.AutoSetText import AutoSetText
from TelegramBot.Handlers.Manual.TranslateText import TranslateText
from TelegramBot.Handlers.Manual.LangChoose import LangChoose
from TelegramBot.Handlers.Manual.EndLangChoose import EndLangChoose
from TelegramBot.Handlers.Manual.SetText import SetText
from TelegramBot.Handlers.BackToTranslateChoose import BackToTranslateChoose
from TelegramBot.Handlers.BackToMenu import BackToMenu
