from TelegramBot.Handlers.Start import StartBot
from TelegramBot.Handlers.Help import HelpComma
from TelegramBot.Handlers.TranslateChoose import ChooseMethod
from TelegramBot.Handlers.Random.RandomWord import RandomTranslate
from TelegramBot.Handlers.Auto.AutoTranslate import AutoTranslateText
from TelegramBot.Handlers.Auto.AutoChooseEndLanguage import AutoEndLangChoose
from TelegramBot.Handlers.Auto.AutoSetText import AutoSetText
from TelegramBot.Handlers.Manual.Translate import TranslateText
from TelegramBot.Handlers.Manual.ChooseLanguage import LangChoose
from TelegramBot.Handlers.Manual.ChooseEndLanguage import EndLangChoose
from TelegramBot.Handlers.Manual.SetText import SetText
from TelegramBot.Handlers.TranslateBack import BackToTranslateChoose
from TelegramBot.Handlers.Back import BackToMenu
